/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ihoneymon' at '14. 1. 26 오후 1:07' with Gradle 1.10
 *
 * @author ihoneymon, @date 14. 1. 26 오후 1:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
